# AUTH {{{

POST http://localhost:13000/signup
Content-Type: application/json

{
    "username": "viktor",
    "password": "viktor"
}

POST http://localhost:13000/login
Content-Type: application/json

{
    "username": "viktor",
    "password": "viktor"
}
# }}}

GET http://localhost:13000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa3RvciIsInN1YiI6MSwiaWF0IjoxNjY4NzYyNTQyLCJleHAiOjE2Njg3NjI2MDJ9.uUS80kLr1lNO6MbFqlLxZAzuxeli00bpad-7iG7zaMQ

# MODELS {{{

curl \
-X POST \
-F file=@test.stl \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa3RvciIsInN1YiI6MSwiaWF0IjoxNjY4NzYyNTQyLCJleHAiOjE2Njg3NjI2MDJ9.uUS80kLr1lNO6MbFqlLxZAzuxeli00bpad-7iG7zaMQ" \
http://localhost:13000/models

# }}}
